### ISSUE TITLE
DatasetView Page Should Retrieve and Pass Down Data

### ISSUE THREAD

**Issue by NathanielScottStevens** [Datastillery/react_discovery_ui#61]
Top level pages should be responsible for sending actions to retrieve data and then passing that data down to its children components instead of those components interacting with the redux store.

Implement this pattern with DatasetView and its children.

**Tech Notes**
* We began to implement this pattern on the branch datasetview-refactor

**Comment by NathanielScottStevens** [comment]
Top level pages should be responsible for sending actions to retrieve data and then passing that data down to its children components instead of those components interacting with the redux store.

Implement this pattern with DatasetView and its children.

**Tech Notes**
* We began to implement this pattern on the branch datasetview-refactor

**Comment by LtChae** [comment]
What are the Acceptance Criteria for this? Should it be *all* components, a subset, etc. Also, should the not really top level components in pages be demoted as part of this process?

**Comment by NathanielScottStevens** [comment]
I think it should be all components underneath DatasetView and any child components using connectors should be demoted to "normal" components.

**Comment by abrock-accenture** [comment]
I'd like to see a list of the components we expect to touch in this card before we point it.

**Comment by LtChae** [comment]
@abrock-accenture Agreed, how do we want to handle that? Who makes the authoritative list?
