### ISSUE TITLE
Write SQL Data Preview Should Better Handle Hierarchical Data

### ISSUE THREAD

**Issue by NathanielScottStevens** [Datastillery/react_discovery_ui#74]
The data preview for the 'Write SQL' tab currently converts objects to strings. We would like to find a more useful way of providing this data to the user.

Some Options:
* Render sub-objects with [expansion toggles](https://codesandbox.io/s/github/tannerlinsley/react-table/tree/master/archives/v6-examples/react-table-pivoting-and-aggregation)
* Provide a modal that shows the sub-object
* Provide a link to another page which shows the json or another table for the sub-object

**Comment by rob-h-m** [comment]
@NathanielScottStevens @carriebrinkley  Help me understand, what "love" is needed to move this card along? Thanks
