### ISSUE TITLE
Geojson preview should show a message when no features are loaded

### ISSUE THREAD

**Issue by jakeprem** [Datastillery/react_discovery_ui#88]
Right now when viewing a GeoJSON dataset with no features, a map view is shown that defaults to Ohio. No features are displayed on the map. It is not clear to the user that no data has been loaded.

Some sort of error message should display to alert the user that no features were retrieved.

AC:
  * When a GeoJSON dataset is loaded with no features returned, show an error or alert message on the page
  * (Optional) Do not show the empty map view when no features are loaded

TN:
  * Talk to @jakeclark about the text and styling of the message to be displayed.

**Comment by mcsearchin** [comment]
We should also handle this by playing smartcitiesdata/discovery_api#278
